version: '3'

services:
  project:
    build:
      context: ./project
      dockerfile: Dockerfile
    volumes:
      - ./project/:/project/
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn server:app --reload --workers 1 --host 0.0.0.0 --port 8080
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
    restart: "on-failure"

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5433:5432
    restart: "on-failure"

volumes:
    postgres_data:
